# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160203_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_body_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_hero_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_optional_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_publication_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 4, 2, 23, 13, 516445, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
