# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160203_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_publication_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
