# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160203_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_hero_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_optional_image',
        ),
    ]
