# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20160203_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_hero_image',
            field=models.ImageField(default=datetime.datetime(2016, 2, 4, 2, 44, 31, 375000, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_optional_image',
            field=models.ImageField(default=datetime.datetime(2016, 2, 4, 2, 44, 44, 335052, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
