# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160203_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_hero_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
